# Generated by Django 4.0.2 on 2022-02-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_prince_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subCategory',
            new_name='sub_category',
        ),
    ]
