# Generated by Django 4.0.2 on 2022-02-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
