# Generated by Django 4.0.2 on 2022-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploadimage',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
